package smc.parser;

public enum ParserState {
  HEADER,
  HEADER_COLON,
  HEADER_VALUE,
  STATE_SPEC,
  SUPER_STATE_NAME,
  SUPER_STATE_CLOSE,
  STATE_MODIFIER,
  EXIT_ACTION,
  ENTRY_ACTION,
  STATE_BASE,
  SINGLE_EVENT,
  SINGLE_NEXT_STATE,
  SINGLE_ACTION_GROUP,
  SINGLE_ACTION_GROUP_NAME,
  SUBTRANSITION_GROUP,
  GROUP_EVENT,
  GROUP_NEXT_STATE,
  GROUP_ACTION_GROUP,
  GROUP_ACTION_GROUP_NAME,
  MULTIPLE_ENTRY_ACTIONS,
  MULTIPLE_EXIT_ACTIONS,
  END
  }
